### ISSUE TITLE
Preferred citation style

### ISSUE THREAD

**Issue by maciejkula** [zygmuntz/goodbooks-10k#2]
I'd like to cite this dataset in my paper. Do you have a preferred citation style? This is what I've come up with:

```
@article{goodbooks2017,
  author = {Zajac, Zygmunt},
  title = {Goodbooks-10K dataset},
  year = {2017},
  publisher = {GitHub},
  journal = {GitHub},
  howpublished = {\url{https://github.com/zygmuntz/goodbooks-10k}},
}
```

**Comment by zygmuntz** [comment]
I plan to write an article about the dataset and I'd prefer people to cite it instead of the repo.

The title will (probably) be "goodbooks-10k: a new dataset for book recommendation"
URL: http://fastml.com/goodbooks-10k-a-new-dataset-for-book-recommendation/
journal/publisher: FastML

The canonical name for the dataset is goodbooks-10k, capitalize to Goodbooks-10k at the beginning of sentence if needed.

When do you need to know for sure? Also, send a link to the paper when ready :)

**Comment by maciejkula** [comment]
I will do that for now and ask again when I'm finalising my draft. Thanks a lot for the dataset, it's been very useful! I'll definitely send a link when done.

**Comment by maciejkula** [comment]
This is what I have now:

```
@article{goodbooks2017,
  author = {Zajac, Zygmunt},
  title = {goodbooks-10k: a new dataset for book recommendations},
  year = {2017},
  publisher = {FastML},
  journal = {FastML},
  howpublished = {\url{https://github.com/zygmuntz/goodbooks-10k}},
}
```

Does it look OK? Can I DM the link to the paper to you on Twitter @fastml?

**Comment by zygmuntz** [comment]
Yes & yes, email would work too. I plan to have the article by the end of November if you can wait.

**Comment by maciejkula** [comment]
I'll be submitting before end of Novemeber, but can always update the arxiv/print version.
